# Find your app's key and secret at http://taskrabbit.com/developers

development:
  key: 
  secret: 
  uri: http://taskrabbitdev.com

test:
  key: 
  secret: 
  uri: http://taskrabbitdev.com

production:
  key: 
  secret: 
  uri: http://taskrabbit.com